/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaimsAdvocacyRouteImport } from './routes/claims-advocacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesMarineRouteImport } from './routes/industries/marine'
import { Route as IndustriesEngineeringInfrastructureRouteImport } from './routes/industries/engineering-infrastructure'
import { Route as IndustriesEnergyRouteImport } from './routes/industries/energy'
import { Route as IndustriesAviationRouteImport } from './routes/industries/aviation'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsAdvocacyRoute = ClaimsAdvocacyRouteImport.update({
  id: '/claims-advocacy',
  path: '/claims-advocacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesMarineRoute = IndustriesMarineRouteImport.update({
  id: '/marine',
  path: '/marine',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesEngineeringInfrastructureRoute =
  IndustriesEngineeringInfrastructureRouteImport.update({
    id: '/engineering-infrastructure',
    path: '/engineering-infrastructure',
    getParentRoute: () => IndustriesRoute,
  } as any)
const IndustriesEnergyRoute = IndustriesEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => IndustriesRoute,
} as any)
const IndustriesAviationRoute = IndustriesAviationRouteImport.update({
  id: '/aviation',
  path: '/aviation',
  getParentRoute: () => IndustriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims-advocacy': typeof ClaimsAdvocacyRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/aviation': typeof IndustriesAviationRoute
  '/industries/energy': typeof IndustriesEnergyRoute
  '/industries/engineering-infrastructure': typeof IndustriesEngineeringInfrastructureRoute
  '/industries/marine': typeof IndustriesMarineRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims-advocacy': typeof ClaimsAdvocacyRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/aviation': typeof IndustriesAviationRoute
  '/industries/energy': typeof IndustriesEnergyRoute
  '/industries/engineering-infrastructure': typeof IndustriesEngineeringInfrastructureRoute
  '/industries/marine': typeof IndustriesMarineRoute
  '/industries': typeof IndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claims-advocacy': typeof ClaimsAdvocacyRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/industries/aviation': typeof IndustriesAviationRoute
  '/industries/energy': typeof IndustriesEnergyRoute
  '/industries/engineering-infrastructure': typeof IndustriesEngineeringInfrastructureRoute
  '/industries/marine': typeof IndustriesMarineRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/claims-advocacy'
    | '/contact'
    | '/industries'
    | '/services'
    | '/sitemap.xml'
    | '/industries/aviation'
    | '/industries/energy'
    | '/industries/engineering-infrastructure'
    | '/industries/marine'
    | '/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/claims-advocacy'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/industries/aviation'
    | '/industries/energy'
    | '/industries/engineering-infrastructure'
    | '/industries/marine'
    | '/industries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/claims-advocacy'
    | '/contact'
    | '/industries'
    | '/services'
    | '/sitemap.xml'
    | '/industries/aviation'
    | '/industries/energy'
    | '/industries/engineering-infrastructure'
    | '/industries/marine'
    | '/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClaimsAdvocacyRoute: typeof ClaimsAdvocacyRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims-advocacy': {
      id: '/claims-advocacy'
      path: '/claims-advocacy'
      fullPath: '/claims-advocacy'
      preLoaderRoute: typeof ClaimsAdvocacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/marine': {
      id: '/industries/marine'
      path: '/marine'
      fullPath: '/industries/marine'
      preLoaderRoute: typeof IndustriesMarineRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/engineering-infrastructure': {
      id: '/industries/engineering-infrastructure'
      path: '/engineering-infrastructure'
      fullPath: '/industries/engineering-infrastructure'
      preLoaderRoute: typeof IndustriesEngineeringInfrastructureRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/energy': {
      id: '/industries/energy'
      path: '/energy'
      fullPath: '/industries/energy'
      preLoaderRoute: typeof IndustriesEnergyRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/industries/aviation': {
      id: '/industries/aviation'
      path: '/aviation'
      fullPath: '/industries/aviation'
      preLoaderRoute: typeof IndustriesAviationRouteImport
      parentRoute: typeof IndustriesRoute
    }
  }
}

interface IndustriesRouteChildren {
  IndustriesAviationRoute: typeof IndustriesAviationRoute
  IndustriesEnergyRoute: typeof IndustriesEnergyRoute
  IndustriesEngineeringInfrastructureRoute: typeof IndustriesEngineeringInfrastructureRoute
  IndustriesMarineRoute: typeof IndustriesMarineRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesAviationRoute: IndustriesAviationRoute,
  IndustriesEnergyRoute: IndustriesEnergyRoute,
  IndustriesEngineeringInfrastructureRoute:
    IndustriesEngineeringInfrastructureRoute,
  IndustriesMarineRoute: IndustriesMarineRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClaimsAdvocacyRoute: ClaimsAdvocacyRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
